[package]
name = "petyaunlocker"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colored = "2.1.0"
disk_list = "0.2.10"
libparted = "0.1.5"
log = "0.4.20"
